language: c

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y -qq valgrind

compiler: 
    - clang
    - gcc

script:
    - make test
    - valgrind --error-exitcode=1 ./bb_test

after_success:
    - bash <(curl -s https://codecov.io/bash)
