language: c

os:
    - linux

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y -qq valgrind

compiler: 
    - clang
    - gcc

script:
    - make valgrind

after_success:
    - bash <(curl -s https://codecov.io/bash)
