language: c
before-install:
        apt-get install -qq valgrind
compiler: 
    - clang
    - gcc

script:
    - make test
    - valgrind --error-exitcode=1 ./bb_test

after_success:
    - bash <(curl -s https://codecov.io/bash)
